replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 27017

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
serviceAccount:
  create: false
  name: ""
ingress:
  enabled: false