replicaCount: 1

image:
  repository: 890742564895.dkr.ecr.us-east-1.amazonaws.com/backend-app
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 5000

env:
  MONGO_URI: mongodb://mongodb:27017/fullstackapp
serviceAccount:
  create: false
  name: ""
ingress:
  enabled: false
